Clean-up and documentation for backend
pythonprofilers/memory_profiler pull request #313
Opened 2021-04-16 04:26 UTC by mgbckr

Here is a first attempt of documenting the backend functionality. I also moved the corresponding test file to examples since that is more appropriate.

2021-04-16 17:09 UTC, fabianp requested changes

2021-04-16 17:09 UTC, fabianp commented on README.rst
> +and is explosed by the API
```suggestion
and is exposed by the API
```

2021-04-16 17:09 UTC, fabianp commented
thanks! other than the minor typo it looks good to me!

2021-04-16 17:10 UTC, fabianp commented
@mgbckr : please feel free to add your name to the end of the README

2021-04-16 20:43 UTC, mgbckr commented
Alright, fixed the typo and added my name, thank you :)

2021-04-19 19:02 UTC, merged

2021-04-19 19:02 UTC, fabianp commented
great, merged